name: ComputerResourceMonitoring CI

 
on: [push]
 
jobs:
  build_and_test:
 
    runs-on: windows-latest
    
    env:
      Test_Project_Path: ComputerMonitoringTests\ComputerMonitoringTests.csproj
      Solution_File_Path: ComputerRessourcesMonitoring\ComputerRessourcesMonitoring.sln
      # Wpf_Project_Path: MyWpfApp\MyWpfApp.csproj
      # Wap_Project_Directory: MyWpfApp.Package
      # Wap_Project_Name: MyWpfApp.Package.wapproj
 
    steps:
      - uses: actions/checkout@v1      
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.207
          
      - name: Setup MSBuild.exe
        uses: warrenbuckley/Setup-MSBuild@v1
          
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2
     
      - name: Restore NuGet Packages
        run: nuget restore $env:Solution_File_Path

      - name: Build
        run: msbuild $env:Solution_File_Path -p:Configuration=Release -p:Platform=x64
        
      - name: Restore for .NET
        run: dotnet restore $env:Solution_File_Path
        
      - name: Execute Unit Tests
        run: dotnet test $env:Solution_File_Path --no-build -p:Configuration=Release -p:Platform=x64