name: ComputerResourceMonitoring CI

 
on: [push]
 
jobs:
  build_and_test:
 
    runs-on: windows-latest
    
    env:
      Test_Project_Path: ComputerMonitoringTests\ComputerMonitoringTests.csproj
      Test_Assembly_Path: ComputerMonitoringTests\bin\Release\ComputerMonitoringTests.dll
      Solution_File_Path: ComputerRessourcesMonitoring\ComputerRessourcesMonitoring.sln
      XUnit_Console: ComputerRessourcesMonitoring\packages\xunit.runner.console.2.4.1\tools\net472\xunit.console
      # Wpf_Project_Path: MyWpfApp\MyWpfApp.csproj
      # Wap_Project_Directory: MyWpfApp.Package
      # Wap_Project_Name: MyWpfApp.Package.wapproj
 
    steps:
      - uses: actions/checkout@v1   
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.207      
          
      - name: Setup MSBuild.exe
        uses: warrenbuckley/Setup-MSBuild@v1
          
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2
     
      - name: Restore NuGet Packages
        run: nuget restore $env:Solution_File_Path       

      - name: Build
        run: msbuild $env:Solution_File_Path -p:Configuration=Release -p:Platform=x64       
        
      - name: Execute Unit Tests
        run: ComputerRessourcesMonitoring\packages\xunit.runner.console.2.4.1\tools\net472\xunit.console $env:Test_Assembly_Path
        
      - name: Generate_Code_Coverage_report
        run: ComputerRessourcesMonitoring\packages\OpenCover.4.7.922\tools\OpenCover.Console.exe -register:user -target:"ComputerRessourcesMonitoring\packages\xunit.runner.console.2.4.1\tools\net472\xunit.console.x86.exe" -targetargs:"ComputerMonitoringTests\bin\Release\ComputerMonitoringTests.dll -noshadow" -output:".\ComputerRessourcesMonitoring\ComputerMonitoringTests_Coverage.xml"
        
      - name: Upload_To_CodeCov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          yml: ./codecov.yml